const KEYS = {
  FILE_LIST: 'FILE_LIST',
  PLUGIN_LIST: 'PLUGIN_LIST',
  EDITOR_PLUGIN_LIST: 'EDITOR_PLUGIN_LIST',
  COMMAND_PLUGIN_LIST: 'COMMAND_PLUGIN_LIST',
  PAGE_DATA: 'PAGE_DATA',
  USER_CONFIG: 'USER_CONFIG',
};
export default KEYS;
